name: Issue2PR

on:
  issues:
    types: 
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: ZanSara/issue2pr@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          issue_number: ${{ github.event.issue.number }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
    
